name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Move Files to Corresponding Folder
              run: |
                  rm -rf /var/www/highfile.ir/html/
                  mkdir -p /var/www/highfile.ir/html/
                  cp -a ./* /var/www/highfile.ir/html/
